        !COMPILER-GENERATED INTERFACE MODULE: Fri Jul 10 13:50:24 2015
        MODULE ALLOCATE_ALL_REWT__genmod
          INTERFACE 
            SUBROUTINE ALLOCATE_ALL_REWT
            END SUBROUTINE ALLOCATE_ALL_REWT
          END INTERFACE 
        END MODULE ALLOCATE_ALL_REWT__genmod
