        !COMPILER-GENERATED INTERFACE MODULE: Fri Jul 10 13:50:24 2015
        MODULE CALC_HILLS__genmod
          INTERFACE 
            SUBROUTINE CALC_HILLS
            END SUBROUTINE CALC_HILLS
          END INTERFACE 
        END MODULE CALC_HILLS__genmod
