        !COMPILER-GENERATED INTERFACE MODULE: Fri Jul 10 13:50:24 2015
        MODULE CALC_HILLS_1D__genmod
          INTERFACE 
            SUBROUTINE CALC_HILLS_1D
            END SUBROUTINE CALC_HILLS_1D
          END INTERFACE 
        END MODULE CALC_HILLS_1D__genmod
