        !COMPILER-GENERATED INTERFACE MODULE: Fri Jul 10 13:50:24 2015
        MODULE CREATE_FILES__genmod
          INTERFACE 
            SUBROUTINE CREATE_FILES
            END SUBROUTINE CREATE_FILES
          END INTERFACE 
        END MODULE CREATE_FILES__genmod
