        !COMPILER-GENERATED INTERFACE MODULE: Fri Jul 10 13:50:24 2015
        MODULE PRINT_ERROR__genmod
          INTERFACE 
            SUBROUTINE PRINT_ERROR(MESSAGE)
              CHARACTER(*) :: MESSAGE
            END SUBROUTINE PRINT_ERROR
          END INTERFACE 
        END MODULE PRINT_ERROR__genmod
