        !COMPILER-GENERATED INTERFACE MODULE: Fri Jul 10 13:50:24 2015
        MODULE PRINT_HILLS_1D__genmod
          INTERFACE 
            SUBROUTINE PRINT_HILLS_1D
            END SUBROUTINE PRINT_HILLS_1D
          END INTERFACE 
        END MODULE PRINT_HILLS_1D__genmod
