        !COMPILER-GENERATED INTERFACE MODULE: Fri Jul 10 13:50:24 2015
        MODULE PRINT_C__genmod
          INTERFACE 
            SUBROUTINE PRINT_C
            END SUBROUTINE PRINT_C
          END INTERFACE 
        END MODULE PRINT_C__genmod
